apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-trial
  annotations:
    consoleName: rhpam-trial
    consoleTitle: BAMOE Trial
    consoleDesc: Deploys a BAMOE Trial environment
spec:
  environment: rhpam-trial
